CREATE SCHEMA IF NOT EXISTS crm;

create table crm.requests
(
    id    bigint generated by default as identity
        constraint pk_base_data
            primary key,
    name text not null,
    description not null,
    sales_id bigint not null,
    client_id bigint not null
);

create table crm.products
(
    id    bigint generated by default as identity
        constraint pk_base_data
            primary key,
    name text not null,
    description not null
);