CREATE SCHEMA IF NOT EXISTS chats;

CREATE TABLE IF NOT EXISTS chats.chats
(
    id bigint generated by default as identity
        constraint pk_chats
            PRIMARY KEY,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    is_disabled boolean default false
);


CREATE TABLE IF NOT EXISTS chats.participants
(
    chat_id bigint not null
        constraint fk_chat_id
        references chats.chats
        on delete restrict,
    user_id bigint not null
        constraint fk_user_id
        references identity.users
        on delete restrict,
    CONSTRAINT pk_participants PRIMARY KEY (chat_id, user_id)
);


CREATE TABLE IF NOT EXISTS chats.anonymous_user
(
    id bigint generated by default as identity
        constraint pk_anonymous_user
        PRIMARY KEY,
    guid_id uuid not null,
    ip inet
    
);
create index if not exists idx_sessions_guid_id on identity.anonymous_user(guid_id);


-- CREATE TABLE IF NOT EXISTS chats.requests
-- (
--     chat_id bigint not null
--         constraint fk_chat_id
--             references chats.chats
--             on delete restrict,
--     lesson_part_id bigint not null
--         constraint fk_practice_id
--             references courses.lessons_parts
--             on delete restrict,
--     CONSTRAINT pk_lessons_parts PRIMARY KEY (lesson_part_id, chat_id)
-- );
-- CREATE TABLE IF NOT EXISTS chats.participants
-- (
--     chat_id bigint not null
--     constraint fk_chat_id
--     references chats.chats
--     on delete restrict,
--     user_id bigint not null
--     constraint fk_user_id
--     references identity.users
--     on delete restrict,
--     CONSTRAINT pk_participants PRIMARY KEY (chat_id, user_id)
--     );

CREATE TABLE IF NOT EXISTS chats.messages
(
    id bigint generated by default as identity
        constraint pk_message
            PRIMARY KEY,
    guid_id uuid not null,
    user_id bigint not null
        constraint fk_user_id
            references identity.users
            on delete restrict,
    reply_id bigint 
        constraint fk_reply_id
            references chats.messages
            on delete restrict,
    data text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create index if not exists idx_sessions_guid_id on identity.sessions(guid_id);