CREATE SCHEMA IF NOT EXISTS files;


create table files.files
(
    id                 bigint generated by default as identity
        constraint pk_files
            primary key,
   
    guid_id            uuid                     not null,
    file_name          varchar(100)             not null,
    file_extension     text                     not null,
    file_name_original text                     not null,
    content_type       varchar(50)              not null,
    data_original      bytea                    not null,
    upload_date        timestamp with time zone not null
);


create unique index ix_files_guid_id
    on files.files (guid_id);

