CREATE SCHEMA IF NOT EXISTS files;


create table files.files
(
    id                 bigint generated by default as identity
        constraint pk_files
            primary key,
    owner_id           bigint                   not null
        constraint fk_files_identity_user_owner_id
            references identity.users
            on delete restrict,
    guid_id            uuid                     not null,
    file_name          varchar(100)             not null,
    file_extension     text                     not null,
    file_name_original text                     not null,
    content_type       varchar(50)              not null,
    data_original      bytea                    not null,
    upload_date        timestamp with time zone not null
);


create unique index ix_files_guid_id
    on files.files (guid_id);

create index ix_files_owner_id
    on files.files (owner_id);