CREATE SCHEMA IF NOT EXISTS profiles;

-- profiles
CREATE TABLE IF NOT EXISTS profiles.profiles
(
    id               bigint generated by default as identity
        constraint pk_profiles
        PRIMARY KEY,
    guid_id          UUID   NOT NULL,
    user_id          bigint
        constraint fk_user_id
        references identity.users
        on delete restrict,
    
    tg_account_id    bigint
    constraint fk_tg_account_id
    references telegram.accounts(id)
    on delete restrict,
    ios_install_id   bigint
    constraint fk_ios_install_id
    references identity.ios_install(id)
    on delete restrict,
    web_anonymous_id bigint
    constraint fk_web_anonymous_id
    references identity.web_anonymous(id)
    on delete restrict

    );
CREATE UNIQUE INDEX IF NOT EXISTS idx_participants_guid_id ON chats.participants (guid_id);
CREATE INDEX IF NOT EXISTS idx_tg_account_id ON chats.participants (tg_account_id) WHERE tg_account_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ios_account_id ON chats.participants (ios_install_id) WHERE ios_install_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_web_anonymous_id ON chats.participants (web_anonymous_id) WHERE web_anonymous_id  IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_participants_chat_id ON chats.participants (chat_id) ;
CREATE INDEX IF NOT EXISTS idx_participants_user_id ON chats.participants (user_id) WHERE user_id IS NOT NULL;
    
-- types
-- Executors, Designers, Showrooms, Vendors    


-- portfolio

-- offices

    
    
    
-- requests



