CREATE SCHEMA IF NOT EXISTS products;




-- плитка двери ламинат шторы
create table products.sections
(
    id    bigint generated by default as identity
        constraint pk_sections
            primary key,
    alias varchar(250)  not null,
    name varchar(250) not null,
    description text
);

create unique index if not exists idx_sections_alias
    on products.sections using btree(alias)
    INCLUDE  (id, name)
    WHERE alias is not null;


create table products.brands
(
    id    bigint generated by default as identity
        constraint pk_brands
            primary key,
    alias varchar(250)  not null,
    name varchar(250) not null,
    description text
);

create unique index if not exists idx_brands_alias
    on products.brands using btree(alias)
    INCLUDE  (id, name)
    WHERE alias is not null
     ;


CREATE TABLE IF NOT EXISTS products.section_brands
(
    section_id bigint not null
        constraint fk_section_brands_section_id
        references products.sections
        on delete restrict,
    brand_id bigint not null
        constraint fk_section_brands_brand_id
        references products.brands
        on delete restrict,
    constraint pk_section_brands
         primary key (section_id, brand_id)
    );


create table products.products
(
    id    bigint generated by default as identity
        constraint pk_base_data
            primary key,
    alias varchar(1024),
    name varchar(1024) not null,
    description text,
    section_id bigint not null
        constraint fk_section_id
            references products.sections(id)
            on delete restrict,
    brand_id bigint not null
        constraint fk_brand_id
            references products.brands(id)
            on delete restrict
);

create index if not exists idx_products_name
    on products.products(name);

create index if not exists idx_products_section_id
    on products.products(section_id);

create index if not exists idx_products_brand_id
    on products.products(brand_id);

