CREATE SCHEMA IF NOT EXISTS products;

create table products.products
(
    id    bigint generated by default as identity
        constraint pk_base_data
            primary key,
    alias text  not null,
    name text not null,
    description not null
);


-- плитка двери ламинат шторы
create table products.sections
(
    id    bigint generated by default as identity
        constraint pk_base_data
            primary key,
    alias text  not null,
    name text not null,
    description not null
);

create unique index if not exists idx_profile_types_alias
    on products.sections(alias)
    INCLUDE  (id, name) -- covering indexes
    using btree(alias);