CREATE SCHEMA IF NOT EXISTS telegram;

CREATE TABLE IF NOT EXISTS telegram.accounts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid_id          UUID        NOT NULL,
    tg_user_id       BIGINT      NOT NULL,
    tg_is_bot        BOOLEAN     NOT NULL DEFAULT FALSE,

    username         VARCHAR(50),
    first_name       TEXT,
    last_name        TEXT,
    language_code    VARCHAR(15),
    is_premium       BOOLEAN,
    phone            VARCHAR(15),
    is_anonymous     BOOLEAN DEFAULT TRUE,
    change_phone_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    added_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    last_seen_at     TIMESTAMPTZ,
    last_message_at  TIMESTAMPTZ
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_accounts_tg_user_id   ON telegram.accounts(tg_user_id);
CREATE UNIQUE INDEX        IF NOT EXISTS idx_accounts_username     ON telegram.accounts(username) WHERE username IS NOT NULL;
CREATE INDEX        IF NOT EXISTS idx_accounts_last_seen    ON telegram.accounts(last_seen_at);
CREATE UNIQUE INDEX        IF NOT EXISTS idx_accounts_guid_id     ON telegram.accounts(guid_id);
CREATE UNIQUE INDEX        IF NOT EXISTS idx_accounts_phone        ON telegram.accounts(phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS telegram.accounts_bots
(
    tg_account_id BIGINT NOT NULL
    REFERENCES telegram.accounts(id) ON DELETE RESTRICT,
    tg_bot_id     BIGINT NOT NULL
    REFERENCES telegram.accounts(id) ON DELETE RESTRICT,
    CONSTRAINT pk_accounts_bots PRIMARY KEY (tg_account_id, tg_bot_id)
    );

CREATE INDEX IF NOT EXISTS idx_tg_bot_id ON telegram.accounts_bots(tg_bot_id);